site_name: PicoCore Documentation
repo_url: https://github.com/PauWol/PicoCore
theme:
  favicon: assets/images/pc.ico
  logo: assets/images/pc.png
  features:
    - navigation.footer
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.blocks.caption

extra:
  social:
    - icon: simple/github
      link: https://github.com/PauWol
copyright: Copyright &copy; 2025 Paul Wolf

nav:
  - Home: index.md
  - About: about.md
  - Getting Started: setup.md
  - Supported Hardware: hardware.md
  - Configuration:
      - Overview: conf/overview.md
      - PicoCore V2:
          - config.toml: conf/v2/config.toml.md
      - Legacy V1: conf/v1-legacy/config.toml.md
  - Usage & API:
      - Overview: api/overview.md
      - V1 Legacy: api/v1-legacy.md
      - V2: api/v2.md
  - Concepts:
      - Services: concepts/services.md
      - P10: concepts/P10.md
      - Tasks: concepts/tasks.md
      - Events: concepts/events.md
      - Timers: concepts/timers.md
      - Power Management: concepts/power.md
  - Examples:
      - Weather Station: examples/weather_station.md
      - Rover: examples/rover.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md
