# PicoOs-Light Configuration File

[system]
name = "PicoOS-Light"
version = "1.0.3"
rtc_sync_stamp = 1757878508

[system.logger]
level = "INFO"
buffersize = 5
max = 600
log_to_console = true
log_to_file = true

[system.health]
onboard_status_led = false
check_interval = 5000
hardwear_cooling = false
hardwear_warming = false


[power]
battery_voltage = 3.3  # Volts
low_battery_warning = 3.0  # Volts